### ISSUE TITLE
local.settings.json wrong value for FUNCTIONS_WORKER_RUNTIME 

### ISSUE THREAD

**Issue by MarteenJL** [MicrosoftDocs/microsoft-cloud#16]
There's seems to be an error in the sample for local.settings.json in the CS , the sample says "node", should be dotnet

"FUNCTIONS_WORKER_RUNTIME": "dotnet",

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3d35c89-5545-3174-d6a1-26b2f3752c7a
* Version Independent ID: e3d35c89-5545-3174-d6a1-26b2f3752c7a
* Content: [Audio/Video Calling from a Custom App into a Teams Meeting](https://learn.microsoft.com/en-us/microsoft-cloud/dev/tutorials/acs-to-teams-meeting?WT.mc_id=m365-80533-dwahlin&tabs=csharp%2Cbash)
* Content Source: [docs/dev/tutorials/acs-to-teams-meeting.yml](https://github.com/MicrosoftDocs/microsoft-cloud/blob/main/docs/dev/tutorials/acs-to-teams-meeting.yml)
* Service: **microsoft-cloud-for-developers**
* GitHub Login: @DanWahlin
* Microsoft Alias: **dwahlin**

**Comment by DanWahlin** [comment]
Thanks @MarteenJL. The person who owns that part of the code is out on maternity leave, but I'll try to take a look as soon as I get a free moment.

//cc @aycabas

**Comment by DanWahlin** [comment]
This has been updated and merged into the repo. Thanks.
