### ISSUE TITLE
README.MD , endoints for Azure functions for .env

### ISSUE THREAD

**Issue by MarteenJL** [MicrosoftDocs/microsoft-cloud#17]
in my copy, the readme.md function did not match the console output for the client's .env

Functions:

        ACSTokenFunction: [GET] http://localhost:7071/api/ACSTokenFunction

        TeamsMeetingFunction: [GET] http://localhost:7071/api/TeamsMeetingFunction

**Comment by DanWahlin** [comment]
Updates made to C# Azure Functions to align the naming.
